version: "3.9"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - vaultwarden-data:/data/
    ports:
      - "8082:80"
      - "3012:3012"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/vaultwarden.conf:ro
      - ${PWD}/crts/:/etc/nginx/crts/:ro
    ports:
      - "82:80"
      - "443:443"
    command: [nginx-debug, "-g", "daemon off;"]

volumes:
  vaultwarden-data:
    name: vaultwarden-data
